apiVersion: v2
name: store-woocommerce
description: Helm chart for deploying a WooCommerce store instance
type: application
version: 1.0.0
appVersion: "6.4"
maintainers:
  - name: Urumi
    email: dev@urumi.ai
