{{- if .Values.resourceQuota.enabled }}
apiVersion: v1
kind: ResourceQuota
metadata:
  name: store-quota
  labels:
    {{- include "store-woocommerce.labels" . | nindent 4 }}
spec:
  hard:
    {{- toYaml .Values.resourceQuota.hard | nindent 4 }}
{{- end }}
---
{{- if .Values.limitRange.enabled }}
apiVersion: v1
kind: LimitRange
metadata:
  name: store-limits
  labels:
    {{- include "store-woocommerce.labels" . | nindent 4 }}
spec:
  limits:
    - type: Container
      default:
        {{- toYaml .Values.limitRange.default | nindent 8 }}
      defaultRequest:
        {{- toYaml .Values.limitRange.defaultRequest | nindent 8 }}
{{- end }}
