apiVersion: v1
kind: Secret
metadata:
  name: mariadb-secret
  labels:
    {{- include "store-woocommerce.labels" . | nindent 4 }}
type: Opaque
data:
  mariadb-root-password: {{ randAlphaNum 24 | b64enc | quote }}
  mariadb-password: {{ randAlphaNum 24 | b64enc | quote }}
  mariadb-database: {{ "wordpress" | b64enc | quote }}
  mariadb-user: {{ "wordpress" | b64enc | quote }}
