apiVersion: apps/v1
kind: Deployment
metadata:
  name: store-platform-api
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "store-platform.labels" . | nindent 4 }}
    app.kubernetes.io/component: api
spec:
  replicas: {{ .Values.replicaCount.api }}
  selector:
    matchLabels:
      app: store-platform-api
  template:
    metadata:
      labels:
        app: store-platform-api
        {{- include "store-platform.labels" . | nindent 8 }}
    spec:
      serviceAccountName: {{ include "store-platform.serviceAccountName" . }}
      containers:
        - name: api
          image: "{{ .Values.image.api.repository }}:{{ .Values.image.api.tag }}"
          imagePullPolicy: {{ .Values.image.api.pullPolicy }}
          ports:
            - name: http
              containerPort: 3001
              protocol: TCP
          envFrom:
            - configMapRef:
                name: store-platform-config
          env:
            - name: PORT
              value: "3001"
          resources:
            {{- toYaml .Values.resources.api | nindent 12 }}
          livenessProbe:
            httpGet:
              path: /api/health/live
              port: 3001
            initialDelaySeconds: 10
            periodSeconds: 15
          readinessProbe:
            httpGet:
              path: /api/health/ready
              port: 3001
            initialDelaySeconds: 5
            periodSeconds: 5
          securityContext:
            runAsNonRoot: true
            runAsUser: 1001
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
