apiVersion: v2
name: store-platform
description: A Helm chart for the Kubernetes Store Provisioning Platform
type: application
version: 1.0.0
appVersion: "1.0.0"
maintainers:
  - name: Urumi
    email: dev@urumi.ai
